Migration guide changes
yandex-maps-unofficial/vue-yandex-maps pull request #119
Opened 2023-12-04 20:09 UTC by zomkd

### 🔗 issue #79

### ❓ Тип изменения

- [x] 📖 Документация
- [ ] 🐞 Исправление ошибки
- [ ] 👌 Улучшение (улучшение того, что уже существует)
- [ ] ✨ Новая фича (не-breaking изменение в проекте)
- [ ] 🧹 Техническое изменение (обновление библиотек, CI/CD и прочие улучшения)
- [ ] ⚠️ Breaking change

### 📚 Description
Added an example to the section YandexMapMarker
Add tips and fix version name

### 📝 Checklist

- [ ] Я приложил(а) Issue или Discussion
- [ x ] Я обновил(а) документацию, если требуется

2023-12-04 21:06 UTC, daniluk4000 requested changes

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/marker.md
> +      <yandex-map-marker v-for="(point, index) in markers" :key="index" :onClick="handleClick" :settings="point">
Поправь чуть форматирование по отступам тут

И onClick надо в settings (предлагаю добавить в markers)

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/marker.md
> +            style="position: relative; width: 20px; height: 20px; background-color: #ff0000; border-radius: 50%; border: 2px solid #ffffff; box-shadow: 0 0 5px rgba(0, 0, 0, 0.5); text-align: center;
А зачем эти стили?

Ну и даже если оставить, давай вынесем в :style объект, строковый style херовенько выглядит

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/marker.md
> +const markers: YMapMarkerProps = [
```suggestion
const markers: YMapMarkerProps[] = [
```

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/marker.md
> +const handleClick = () => {
Еще предлагаю добавить тут аргументы которые есть у Яндекса для этого листенера, и тип листенера (он у них есть в типизации)

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/marker.md
> +```vue
Добавь ### Пример использования заголовочек

И может добавим информацию про пример кода в 0.x/1.x? Как ::: tip мб

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/list.md
> +::: tip Совет
```suggestion
::: tip Важно
```

2023-12-04 21:06 UTC, daniluk4000 commented on docs/components/list.md
> +::: tip Совет
```suggestion
::: tip Важно
```

2023-12-05 07:49 UTC, zomkd commented on docs/components/marker.md
> +            style="position: relative; width: 20px; height: 20px; background-color: #ff0000; border-radius: 50%; border: 2px solid #ffffff; box-shadow: 0 0 5px rgba(0, 0, 0, 0.5); text-align: center;
хотел показать, что можно использовать кастомные маркеры с HTML

2023-12-05 10:09 UTC, zomkd commented on docs/components/marker.md
> +```vue
Я по аналогии с разделом YandexMapListener сделал. Наверно, надо examples сделать  с кодом, чтобы можно было посмотреть и пощупать и на него ссылаться
Могу заняться

2023-12-05 11:41 UTC, daniluk4000 commented on docs/components/marker.md
> +```vue
Сделай пример ДО/ПОСЛЕ для 1.х пожалуйста и достаточно в целом

2023-12-05 11:42 UTC, daniluk4000 requested changes

2023-12-05 11:42 UTC, daniluk4000 commented on docs/components/marker.md
> +```vue
И заголовочек всё таки нужен тут

2023-12-05 11:42 UTC, daniluk4000 commented on docs/components/marker.md
> +const styleObject: CSSProperties = {
Я думал ты прям в HTML сделаешь, как у меня в секции Примеры, но тоже сойдет)

2023-12-05 14:56 UTC, merged